server:
  host: "0.0.0.0"
  port: 10010
  debug: false
  autoreload: false

app:
  name: "DataFinderAgentOS"
  title: "智能瞭望与问数系统"
  version: "1.0.0"

session:
  cookie_secret: "datafinder-token-2025-secure"
  login_url: "/"
  xsrf_cookies: true

template:
  path: "app/templates"

static:
  path: "app/static"